server:
  port: 8092

spring:
  application:
    name: hotel-api
  datasource:
    url: jdbc:h2:mem:hoteldb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  info:
    title: SerwisRest API Documentation
    description: Restful API for hotel.
    contact:
      name: Darya Huseva
      email: dorothy.dmitrievna@gmail.com
  pathsToMatch: /property-view/**